name: Stylelint

on:
  push:
    branches: ["develop"]
  pull_request:
    branches: ["develop"]

jobs:
  styleLint:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install and styleLint Client
        working-directory: ./client
        run: |
          npm ci
          npm run lint:css
